# fly.toml app configuration file generated for commu-platform on 2024-02-08T22:43:02+10:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'commu-platform'
primary_region = 'syd'

[build]
  image = 'cyrusnguyen/commapp:latest'

[env]
  ASPNETCORE_URLS="http://+:8080"
  CloudinarySettings__CloudName="dptaltqdt"
  CloudinarySettings__ApiKey="347677988953162"
  
[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024
